---
create_containers: 1
default_container_name: haim_docker
default_container_image: nginx
default_container_command: * /usr/share/nginx/html
http_host: "haim_domain"
http_conf: "haim_domain.conf"
http_port: "80"